spring:
  application:
    name: FinGest

  ########### DataBase Properties #################
  ### Postgresql database properties
  ## Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/fingestdb
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  ## JPA properties
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

